ALTER TABLE [dbo].[domain_word]
    ADD CONSTRAINT [PK_domain_word] PRIMARY KEY CLUSTERED ([domain_id] ASC, [word_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

