ALTER TABLE [dbo].[film_part]
    ADD CONSTRAINT [PK_film_part] PRIMARY KEY CLUSTERED ([film_id] ASC, [number] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

