ALTER TABLE [dbo].[account_verb]
    ADD CONSTRAINT [PK_account_verb] PRIMARY KEY CLUSTERED ([account_id] ASC, [verb_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

